# Generated by Django 5.2.4 on 2025-07-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_response', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedmessage',
            name='language',
            field=models.CharField(default='en', help_text='Language of the message', max_length=10),
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='message_text',
            field=models.TextField(default='xxx', help_text='Message content (original or transcribed)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('voice', 'Voice Message')], default='text', help_text='Type of message', max_length=10),
        ),
    ]
