# Generated by Django 5.2.4 on 2025-07-26 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_response', '0002_receivedmessage_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedmessage',
            name='conversation_status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', help_text='Status of the conversation', max_length=20),
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='conversation_step',
            field=models.PositiveIntegerField(default=1, help_text='Step number in conversation (1=initial)'),
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='follow_up_question',
            field=models.TextField(blank=True, help_text='Question asked for follow-up'),
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='is_conversation_starter',
            field=models.BooleanField(default=True, help_text='Whether this starts a new conversation'),
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='needs_follow_up',
            field=models.BooleanField(default=False, help_text='Whether AI requested more information'),
        ),
        migrations.AddField(
            model_name='receivedmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, help_text='Parent message if this is a follow-up', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='first_response.receivedmessage'),
        ),
    ]
